### ISSUE TITLE
Custom commands not showing

### ISSUE THREAD

**Issue by OwenMelbz** [codestudiohq/laravel-totem#12]
Hi, loving the idea of this package so wanted to give it a go.

We've got around 15 custom commands which are registered in the `Console/Kernel.php` and we run via the normal laravel scheduler.

However none of these commands are showing on the Totem create task screen.

Is there something we need to do to make these show?

Thanks

**Comment by roshangautam** [comment]
Thanks for pointing this out.

Reason : Totem overrides Laravel's core Console kernel which means the Console Kernel residing in your app/Console folder is no longer valid. This leaves us to the question , how do we register commands. You can do it in two different ways:

1. Move your commands variables to your app/Providers/AppServiceProvider and in the register method add the following

```
$this->commands($this->commands);
```

2. Roll your own ConsoleServiceProvider in app/Providers, move your commands variable to ConsoleServiceProvider and in its register method add the following. Don't forget to add this new provider to config/app.php's providers array.

```
$this->commands($this->commands);
```

From L5.5 all the commands are auto registered, so this wouldn't be a problem. Hope this helps. I should probably add this to installation instruction in readme.

**Comment by roshangautam** [comment]
@OwenMelbz : did you get your issue resolved ?

**Comment by OwenMelbz** [comment]
Not yet, will be back at work tomorrow so can have a look then :)

**Comment by vonec** [comment]
please do asap 👍

**Comment by roshangautam** [comment]
Thanks for the feedback @vonec 

5.4 requires command registration for it to work. Also horizon requires 5.5 and above as far as I know.

> add commands directly rather than select box
Are you trying to say all the traditionally scheduled tasks should be added automatically ?

All scheduled tasks actually run through Laravel's scheduler as they would if scheduled traditionally. As far as I know Laravel do no have a timeout or max duration for long running tasks. Also, as they are run through a system process on your server you really don't have to worry about long running tasks.

**Comment by vonec** [comment]
Horizon runs on laravel 5.4 :)

Not all the traditional tasks , i had to include the Horizon task manually to get it to the select box, there could be a manual input too for custom commands

i have a long running task that takes around 30 minutes to complete, i executed it manually, it worked well, but  AVERAGE RUNTIME is 0
--

**Comment by roshangautam** [comment]
@vonec did you try refreshing the page ? The execute button makes an xhr request and currently doesn't refresh the page after completion.

**Comment by roshangautam** [comment]
@OwenMelbz . The new changes now let you schedule tasks traditionally from app/Console/Kernel.php in addition from Totem's dashboard. Also commands registered in app/Console/Kernel should show in the select list without any additional work as suggested before. Please update to latest alpha for the changes. Don't forget to republish totem assets after updating.

**Comment by vonec** [comment]
sure will update :)

**Comment by vonec** [comment]
I updated the package and here are my test results


Good: Add New Task has all the hints it required.

Bad: We moved our custom commands back to App/Console/Kernel but they are not yet visible in the dropdown ... I have published the assets.

**Comment by OwenMelbz** [comment]
@roshangautam I can confirm with version `v0.7.0` we're also not seeing custom commands that use the default laravel registration system

**Comment by roshangautam** [comment]
Can you guys please try master branch and see what happens ? Just pushed a change to make this work. @OwenMelbz @vonec 

Thanks

**Comment by mrmonat** [comment]
@roshangautam I had the same issue, with "dev-master" it works like expected.

**Comment by roshangautam** [comment]
Thanks @mrmonat . I am refactoring a bit more , once done I will tag another alpha.

**Comment by vonec** [comment]
just to add it up why are there so many info logs ? cant that be disabled through config

**Comment by roshangautam** [comment]
Thanks for reporting. The logs should unlink once after the task has executed. I will check whats going on.  Also closing this issue as the original issue is now resolved in master branch. Please open a new issue for any other questions or problems.

Thanks.

**Comment by alexstone** [comment]
I'm currently in 5.5 and the custom commands are still not showing up in the task create list

**Comment by roshangautam** [comment]
@alexstone Just tagged a new alpha. Please update to receive changes regarding custom commands.

**Comment by alexstone** [comment]
@roshangautam I got my commands to show up when I manually register them. But in 5.5, the auto-registered commands still don't show up in the list. Any ideas? For context, I upgraded from 5.4 to 5.5. My commands all appear in the console when I do `php artisan list`.

**Comment by roshangautam** [comment]
I have opened an [issue](https://github.com/laravel/internals/issues/770) in laravel/internals.  In the mean time I will add a custom Kernel to handle this in totem. This shouldn't effect other functionalities.

**Comment by roshangautam** [comment]
@alexstone can you please pull in the master branch and try this again. I have made some changes to make this work.

**Comment by roshangautam** [comment]
This should be working fine in master branch.

**Comment by alexstone** [comment]
Confirming that it works! Thank you!
